---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificates-greyroom-net-production
  namespace: argocd
spec:
  secretName: argocd-certificates-greyroom-net-production
  issuerRef:
    name: issuer-letsencrypt-production
    kind: ClusterIssuer
  commonName: "argocd.greyroom.net"
  dnsNames:
    - "argocd.greyroom.net"
