{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "garage-s3-longhorn-bucket-credentials",
    "namespace": "longhorn-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "garage-s3-longhorn-bucket-credentials",
        "namespace": "longhorn-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAfPDnQyHDST2XqhFOgDXSlKoXhCwzt5V2U0UAkp9SyE49bhNrVTj7yV5aDZ3ile9shvBrcsxWHWmYlF4/9EMzeoUKQ966TrVfZOxwgX3sQKNtEmsFgJNFr/auOGuR8U+82gv3V1e3ldAIcwgzMOW2joPsi1hVdJLG5XGuEXfmze5IHUc7yRu+XrB/z0iE46XV2XCdrz6fNp467jWtLeEVfRbvi4ohTwNfxNcDF4T/UrnY0CPhOcvh7HXvDH2YLvCZXAqNkNb6OdA2wdqMRukV/MKnwBnaMakZjWFekUKNi6RQkRmizLu/nd1EAaxpn775m7eJjDfysc5ze9EHpBVOJWco2XHBjLxI0G49zl/Y9a143cvuXUyoAU+qIsYCYM1KiiI3PJ5gz1mZikfjpf5LMeEiN5ZLVv6cqOGXybxeA4NccHzGQmfsvZTPuojzuB11gggvz8A5iFNAoPqLvj9NE/p0qnC4Yr5s1SKdM+XhLHFWs6OWv1MkKCsmDKfLNdHuDqayMhxd1wjXZ2c6EOMHhMqP8R+APVwk/gqov7bSv9H/gclstG7nsPqBh4AsD4FCx+LYS2AFRpCRsx0yzr4BKESSrYUPLRn6o8hh1KZDlVmwi1D343jcPbrgly8rHm+Bwh91GHYq5c2k0j2ofm8N1hzt6z0zW5+3Rkwn0+5ewM0Rsr0kTjSqIDlwsLQhzDohE3VTOsrPDh2s6Hk0IXsZUa3A4c/NPqkLo2g==",
      "AWS_ENDPOINTS": "AgBwhayFFch2bj94bLAF3+90hNT5BQvd6sag3OTPMA2qR6XfCIxPmXxlUBFKqTqVFbmBkC6asJcI0nhrZ2JrQLpTe4fR0gHcYbMRIhk+LHdvhWqWkVYqu80n8k1yaKbk7lv3d35tEQDHk8UnmAXKHql1Pu1oDm6lQTSy4GLA+ot3uFfgWGorurIoz9eQr75tL1wvd2SC6DKA5nPZ1Vh10eAjc/sT3YatF28UHsebNw4+TRBVI1eeJo6Lg5c7kE92JumAL6z4MqViTZWrcJ1qPe6v8+7sscO5pKCpHSS1LXRZU1AjPWpjLsRrehv6lXt25TJrN0XRqjX/jRuMNOBxHVzQmVF6Z0p29gQeXINQkVgQdtGiFsYMK/iWXXX8saeC67qV3h1aeeZAtPhheQ2uGLsJoAbZrqiLYJ8R10FPGSFB2CS79VLMb2FS9ArxSFp5nsXPsWD5rNG4YQxHYlApcUqo7P4p3B4JZH07U5fg6wBNBmSp0fG6jzm8pw902ADkAijXa4XZPPKiB5VCJKkubRXPwkrbKYQqXmpnnN10T+6160KrX1fmyFNuyhFjvfHr8ieybg1o0SbLNBNPpCplscQXkiA3OsD/CB011dKjX6RF1mR0+Lt/GlnLbEtW6gjWt/EE5yKLduqKxYm9ohzvVA4G4l5ieztRYxzhSNKdbHX3P1kd/bKRPy2O9r3oJ7PH3z6fY/smKVaZfaxy/xcV6I3hT/d9Jg0rBq4iOLM=",
      "AWS_SECRET_ACCESS_KEY": "AgDQxxZF2GxLZ1//w6fwAHdWV//cX2vr7rl+H4FI/1Z3gO1ARVmiXOtZpP6KKvTUA8YMiue0tCr8oShNV9w3HwlnvOUX3sabBY8v2+KXN8t1zZQ8fuRDQuRV/TLLf48Wr3Q/vzwRLcFdS7oysiiKrXCCZT5pZMy/zbhhT4CODCLHGpXmDXJZ4kkqMP4umwo+44reYDKmXYU5agaNRZm22Fq8ZrcjaKBEXWzOtot6SKMoZzbu3RCJkXAgr+Mrqhv9vNhiuAHoyx7QqFrnADwmuy/Nmg2G8Zge86IWYq/+gucGlsioG5YGunRcMttTEshDid3RqAikYaV/MoIo7Wmve831+DOOIfhPUU5mAD+k5gKck/xvW3DpwVl7V+byUhMcem7Vn+ZGn9WdkeMU5KvDS1/+zGtH8VszaWZqPez2NO+umaBFBu2gz5Xj11c+tprf8NHEFtgIwzrwUkXmyLM82+sU6KCpna1u1//tHSwyKlkxJ6Y0eUijppaCsmRinUpZdROWAWUwZz6rWc44mfAtg4Tc8yr9348PCDgfiGdVksM3dRSVCmbK4vW4L7bqtRRr9OIkTWyBsKaLSaZoJjl/HOJXUnmBc1UyetXstzMJ6iQfaDDT47VBaAGaX6lLa5V2ca2NpEcwTNVZPQZImRxDs4veh+xBcVLmaADIIR+DZK58d+KvpjsaYu0jUZF3NneswfafzJ4i4XPSrhbWUeuLnpsCaIRHjNhCHIaWmH7SRNPIvOtFRmhmfb77bV/UT7bVh/GGo9Beo+xv34KuHjII/TjS"
    }
  }
}
