---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mattia.vallortigara@protonmail.com
    privateKeySecretRef:
      name: issuer-letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: mattia.vallortigara@protonmail.com
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key